/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ExcalidrawUserIdRouteImport } from './routes/excalidraw/$userId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExcalidrawUserIdRoute = ExcalidrawUserIdRouteImport.update({
  id: '/excalidraw/$userId',
  path: '/excalidraw/$userId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/excalidraw/$userId': typeof ExcalidrawUserIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/excalidraw/$userId': typeof ExcalidrawUserIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/excalidraw/$userId': typeof ExcalidrawUserIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/excalidraw/$userId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/excalidraw/$userId'
  id: '__root__' | '/' | '/excalidraw/$userId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ExcalidrawUserIdRoute: typeof ExcalidrawUserIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/excalidraw/$userId': {
      id: '/excalidraw/$userId'
      path: '/excalidraw/$userId'
      fullPath: '/excalidraw/$userId'
      preLoaderRoute: typeof ExcalidrawUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ExcalidrawUserIdRoute: ExcalidrawUserIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
